CREATE TABLE product (
  `ID` VARCHAR(255) NOT NULL ,
  `NAME` VARCHAR(255) NULL,
  `CATEGORY` VARCHAR(255) NULL,
  `SUBCATEGORY` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`));
LOAD DATA LOCAL INFILE 'C:/Users/nhuma/Downloads/Technical Test/Product.csv' 
INTO TABLE product
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS (`ID`,`NAME`,`CATEGORY`,`SUBCATEGORY`);
CREATE TABLE order (
  `ROW_ID` VARCHAR(255) NOT NULL ,
  `ORDER_ID` VARCHAR(255) NOT NULL ,
  `ORDER_DATE` DATE,
  `SHIP_DATE` DATE,
  `SHIP_MODE` VARCHAR(255) NULL,
  `CUSTOMER_ID` VARCHAR(255) NOT NULL ,
  `PRODUCT_ID` VARCHAR(255) NOT NULL ,
  `SALES` DOUBLE(6,4),
  `QUANTITY` INT(25),
  `DISCOUNT` DECIMAL(3,2),
  `PROFIT` DOUBLE(6,4),
  PRIMARY KEY (`ID`));
 